#%RAML 1.0 NamedExample
  {
    "Account Name" : " Harry",
    "phone": "(336)254545",
    "Billing City" : "Pune",
    "Billing Country" : "India",
    "Billing Zip/Postam Code" : "411004",
    "Billing Street" : "S.B road",
    "Account Number" : "CD455455"
  }