#%RAML 1.0 DataType
properties:
  Account Name: string
  phone: number
  Billing City: string
  Country: string
  Billing Country: string
  Billing Zip/Postam Code: number
  Billing Street:  string
  Account Number: string
  
  